# Generated by Django 3.1.3 on 2020-11-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='salary',
            new_name='score',
        ),
    ]
